# Generated by Django 5.2 on 2025-11-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('spray', 'Spray'), ('roll-on', 'Roll-on'), ('serum', 'Serum'), ('barra', 'Barra'), ('ungüento', 'Ungüento')], default='spray', max_length=20, verbose_name='Tipo de presentación'),
        ),
    ]
