# Generated by Django 5.2 on 2025-11-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeCintillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Texto del mensaje')),
                ('enlace', models.CharField(blank=True, help_text="Opcional. Ej: '/cosmetica' para interno o 'https://instagram.com' para externo.", max_length=255, null=True)),
                ('activo', models.BooleanField(default=True, verbose_name='¿Mostrar en la web?')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición')),
            ],
            options={
                'verbose_name': 'Mensaje Cintillo',
                'verbose_name_plural': 'Mensajes Cintillo',
                'ordering': ['orden'],
            },
        ),
    ]
