# Generated by Django 5.2 on 2025-12-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mensajecintillo'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='aplicar_a_todos',
            field=models.BooleanField(default=False, help_text="Si marcas esto, la oferta aplicará a todos los productos, excepto los que pongas en 'excluidos'.", verbose_name='¿Aplicar a TODO el catálogo?'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='productos_excluidos',
            field=models.ManyToManyField(blank=True, help_text='Si aplicas a todos, selecciona aquí los que NO quieres que tengan descuento.', related_name='ofertas_excluidas', to='core.producto', verbose_name='Productos excluidos'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='productos',
            field=models.ManyToManyField(blank=True, help_text='Selecciona productos si la oferta es solo para algunos.', related_name='ofertas', to='core.producto', verbose_name='Productos específicos'),
        ),
    ]
